# Generated by Django 4.2 on 2026-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombres')),
                ('Apellido', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('NumCedula', models.CharField(max_length=20, unique=True, verbose_name='Número de Cédula')),
                ('NumTelefono', models.IntegerField(verbose_name='Número de Teléfono')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('Estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
