# Generated by Django 4.2 on 2026-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionEstado', models.CharField(max_length=30, unique=True, verbose_name='Descripción del Estado')),
                ('Estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Estados de Cuenta',
            },
        ),
    ]
