# Generated by Django 4.2 on 2026-07-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCaja', models.IntegerField(unique=True, verbose_name='Número de Caja')),
                ('Estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
